"""Public API for deterministic Framework Assignment.

The package exposes persona-local proposals, deterministic consensus,
non-authoritative persistence, and read-only reference validation. Human
acceptance and target-model mutation remain outside this package.
"""

from modules.framework_assignment.agent_manifest import (
    FRAMEWORK_ASSIGNMENT_AGENT_RESULT_SCHEMA_VERSION,
    create_framework_assignment_agent_candidate,
    create_framework_assignment_agent_result,
    create_framework_assignment_basis,
    create_framework_assignment_proposal,
    framework_assignment_agent_result_from_json,
    framework_assignment_agent_result_to_dict,
    framework_assignment_agent_result_to_json,
    parse_framework_assignment_agent_result,
    validate_framework_assignment_agent_result,
)
from modules.framework_assignment.analyzer import (
    FRAMEWORK_ASSIGNMENT_CONSENSUS_SCHEMA_VERSION,
    FRAMEWORK_ASSIGNMENT_SIGNATURE_ID,
    FRAMEWORK_ASSIGNMENT_SIGNATURE_VERSION,
    FrameworkAssignmentConsensusResult,
    analyze_framework_assignment_consensus,
    framework_assignment_signature,
)
from modules.framework_assignment.candidate_manifest import (
    FRAMEWORK_ASSIGNMENT_CANDIDATE_SCHEMA_VERSION,
    calculate_framework_assignment_fingerprint,
    create_framework_assignment_candidate,
    framework_assignment_candidate_from_json,
    framework_assignment_candidate_to_dict,
    framework_assignment_candidate_to_json,
    parse_framework_assignment_candidate,
    validate_framework_assignment_candidate,
)
from modules.framework_assignment.errors import (
    DuplicateFrameworkAssignmentAgentCandidateError,
    DuplicateFrameworkAssignmentAgentResultError,
    DuplicateFrameworkAssignmentCandidateError,
    FrameworkAssignmentAgentCandidateIdAllocationError,
    FrameworkAssignmentCandidateIdAllocationError,
    FrameworkAssignmentComparisonError,
    FrameworkAssignmentConfigurationError,
    FrameworkAssignmentError,
    FrameworkAssignmentIntegrityError,
    FrameworkAssignmentPersistenceError,
    FrameworkAssignmentReferenceError,
    FrameworkAssignmentValidationError,
    IncomparableFrameworkAssignmentClusterError,
)
from modules.framework_assignment.identifiers import (
    MAX_FRAMEWORK_ASSIGNMENT_SEQUENCE,
    MIN_FRAMEWORK_ASSIGNMENT_SEQUENCE,
    format_framework_assignment_agent_candidate_id,
    format_framework_assignment_candidate_id,
    framework_assignment_agent_candidate_id_sequence,
    framework_assignment_candidate_id_sequence,
    is_valid_framework_assignment_agent_candidate_id,
    is_valid_framework_assignment_candidate_id,
    next_framework_assignment_agent_candidate_id,
    next_framework_assignment_candidate_id,
    validate_framework_assignment_agent_candidate_id,
    validate_framework_assignment_candidate_id,
)
from modules.framework_assignment.reference_validation import (
    FrameworkAssignmentReferenceValidationResult,
    validate_framework_assignment_references,
)
from modules.framework_assignment.repository import (
    FRAMEWORK_ASSIGNMENTS_DIRECTORY_NAME,
    SEMANTICS_DIRECTORY_NAME,
    FrameworkAssignmentRepository,
)
from modules.framework_assignment.types import (
    FRAMEWORK_ASSIGNMENT_BASIS_TYPES,
    FRAMEWORK_ASSIGNMENT_CONFIDENCE_LEVELS,
    FRAMEWORK_ASSIGNMENT_CONSENSUS_LEVELS,
    FRAMEWORK_ASSIGNMENT_ISSUE_LEVELS,
    FRAMEWORK_ASSIGNMENT_REVIEW_MODES,
    FRAMEWORK_ASSIGNMENT_STATUSES,
    FRAMEWORK_ASSIGNMENT_VARIANCE_LEVELS,
    FrameworkAssignmentAgentCandidate,
    FrameworkAssignmentAgentCandidateReference,
    FrameworkAssignmentAgentResult,
    FrameworkAssignmentBasis,
    FrameworkAssignmentCandidate,
    FrameworkAssignmentConsensusOutcome,
    FrameworkAssignmentIssue,
    FrameworkAssignmentProposal,
    FrameworkAssignmentScanResult,
    FrameworkAssignmentValueDistribution,
)


__all__ = (
    "FRAMEWORK_ASSIGNMENTS_DIRECTORY_NAME",
    "FRAMEWORK_ASSIGNMENT_AGENT_RESULT_SCHEMA_VERSION",
    "FRAMEWORK_ASSIGNMENT_BASIS_TYPES",
    "FRAMEWORK_ASSIGNMENT_CANDIDATE_SCHEMA_VERSION",
    "FRAMEWORK_ASSIGNMENT_CONFIDENCE_LEVELS",
    "FRAMEWORK_ASSIGNMENT_CONSENSUS_LEVELS",
    "FRAMEWORK_ASSIGNMENT_CONSENSUS_SCHEMA_VERSION",
    "FRAMEWORK_ASSIGNMENT_ISSUE_LEVELS",
    "FRAMEWORK_ASSIGNMENT_REVIEW_MODES",
    "FRAMEWORK_ASSIGNMENT_SIGNATURE_ID",
    "FRAMEWORK_ASSIGNMENT_SIGNATURE_VERSION",
    "FRAMEWORK_ASSIGNMENT_STATUSES",
    "FRAMEWORK_ASSIGNMENT_VARIANCE_LEVELS",
    "MAX_FRAMEWORK_ASSIGNMENT_SEQUENCE",
    "MIN_FRAMEWORK_ASSIGNMENT_SEQUENCE",
    "SEMANTICS_DIRECTORY_NAME",
    "DuplicateFrameworkAssignmentAgentCandidateError",
    "DuplicateFrameworkAssignmentAgentResultError",
    "DuplicateFrameworkAssignmentCandidateError",
    "FrameworkAssignmentAgentCandidate",
    "FrameworkAssignmentAgentCandidateIdAllocationError",
    "FrameworkAssignmentAgentCandidateReference",
    "FrameworkAssignmentAgentResult",
    "FrameworkAssignmentBasis",
    "FrameworkAssignmentCandidate",
    "FrameworkAssignmentCandidateIdAllocationError",
    "FrameworkAssignmentComparisonError",
    "FrameworkAssignmentConfigurationError",
    "FrameworkAssignmentConsensusOutcome",
    "FrameworkAssignmentConsensusResult",
    "FrameworkAssignmentError",
    "FrameworkAssignmentIntegrityError",
    "FrameworkAssignmentIssue",
    "FrameworkAssignmentPersistenceError",
    "FrameworkAssignmentProposal",
    "FrameworkAssignmentReferenceError",
    "FrameworkAssignmentReferenceValidationResult",
    "FrameworkAssignmentRepository",
    "FrameworkAssignmentScanResult",
    "FrameworkAssignmentValidationError",
    "FrameworkAssignmentValueDistribution",
    "IncomparableFrameworkAssignmentClusterError",
    "analyze_framework_assignment_consensus",
    "calculate_framework_assignment_fingerprint",
    "create_framework_assignment_agent_candidate",
    "create_framework_assignment_agent_result",
    "create_framework_assignment_basis",
    "create_framework_assignment_candidate",
    "create_framework_assignment_proposal",
    "format_framework_assignment_agent_candidate_id",
    "format_framework_assignment_candidate_id",
    "framework_assignment_agent_candidate_id_sequence",
    "framework_assignment_agent_result_from_json",
    "framework_assignment_agent_result_to_dict",
    "framework_assignment_agent_result_to_json",
    "framework_assignment_candidate_from_json",
    "framework_assignment_candidate_id_sequence",
    "framework_assignment_candidate_to_dict",
    "framework_assignment_candidate_to_json",
    "framework_assignment_signature",
    "is_valid_framework_assignment_agent_candidate_id",
    "is_valid_framework_assignment_candidate_id",
    "next_framework_assignment_agent_candidate_id",
    "next_framework_assignment_candidate_id",
    "parse_framework_assignment_agent_result",
    "parse_framework_assignment_candidate",
    "validate_framework_assignment_agent_candidate_id",
    "validate_framework_assignment_agent_result",
    "validate_framework_assignment_candidate",
    "validate_framework_assignment_candidate_id",
    "validate_framework_assignment_references",
)