"""Exact Final Model Review revision -> Published Output bridge."""

from __future__ import annotations

from modules.sysml_generation.authority_backed import (
    AuthorityBackedGeneratedSysMLArtifactSet,
    authority_backed_artifact_set_from_json,
)

from dataclasses import fields, is_dataclass, replace
from pathlib import Path
import json
import types
from typing import Any, Union, get_args, get_origin, get_type_hints

from modules.final_model_review.release_gate import (
    require_final_model_review_approved_for_publication,
)
from modules.final_model_review.repository import (
    FinalModelReviewRepository,
)
from modules.sysml_generation.types import (
    GeneratedSysMLArtifactSet,
)
from modules.sysml_validation.phase_l_gate import (
    validate_phase_l_handoff,
)
from modules.sysml_validation.types import (
    SysMLValidationResult,
)

from .errors import OutputPublicationIntegrityError
from .writer import OutputWriter


class FinalReviewPublicationService:
    """Publish one explicit immutable Final Model Review revision.

    The service performs no regeneration and no revalidation. It reconstructs
    the exact persisted Phase-J / Phase-K transfer objects from the selected
    FRV, verifies the stored generated bytes, resolves the persisted Human
    approval for that exact revision and delegates final publication to
    OutputWriter.
    """

    def __init__(
        self,
        project_root: Path | str = Path("."),
        *,
        final_review_repository=None,
        output_writer=None,
        release_gate_resolver=require_final_model_review_approved_for_publication,
        phase_l_gate=validate_phase_l_handoff,
    ) -> None:
        self.project_root = Path(project_root)
        projects_root = self.project_root / "data" / "projects"

        self._reviews = (
            FinalModelReviewRepository(root=projects_root)
            if final_review_repository is None
            else final_review_repository
        )
        self._writer = (
            OutputWriter(
                output_root=self.project_root / "data" / "output",
                project_root=projects_root,
                final_review_repository=self._reviews,
            )
            if output_writer is None
            else output_writer
        )
        self._release_gate_resolver = release_gate_resolver
        self._phase_l_gate = phase_l_gate

    def publish_revision(
        self,
        project_id: str,
        final_model_review_id: str,
        final_model_review_revision_id: str,
    ):
        """Publish only the exact explicitly selected approved FRV."""

        try:
            bundle = self._reviews.load_revision(
                project_id,
                final_model_review_id,
                final_model_review_revision_id,
            )
        except Exception as exc:
            raise OutputPublicationIntegrityError(
                "Final Model Review revision could not be loaded exactly."
            ) from exc

        revision = bundle.revision

        if (
            revision.project_id != project_id
            or revision.final_model_review_id != final_model_review_id
            or revision.final_model_review_revision_id
            != final_model_review_revision_id
        ):
            raise OutputPublicationIntegrityError(
                "Loaded Final Model Review revision does not match the "
                "explicit publication target."
            )

        try:
            release_gate = self._release_gate_resolver(
                self._reviews,
                project_id,
                final_model_review_id,
                final_model_review_revision_id,
            )
        except Exception as exc:
            raise OutputPublicationIntegrityError(
                "The selected Final Model Review revision is not approved "
                "for publication."
            ) from exc

        approval_decision_id = getattr(
            release_gate,
            "approval_decision_id",
            None,
        )
        if not isinstance(approval_decision_id, str):
            raise OutputPublicationIntegrityError(
                "Approved release gate does not resolve an exact Human "
                "approval decision."
            )

        try:
            decision = self._reviews.load_decision(
                project_id,
                final_model_review_id,
                approval_decision_id,
            )
        except Exception as exc:
            raise OutputPublicationIntegrityError(
                "Persisted Human publication approval could not be loaded."
            ) from exc

        self._validate_approval_target(
            decision,
            project_id=project_id,
            review_id=final_model_review_id,
            revision_id=final_model_review_revision_id,
        )

        artifact_set = self._artifact_set_from_bundle(bundle)
        validation_result = self._validation_result_from_bundle(bundle)

        if (
            artifact_set.content_fingerprint
            != revision.generated_artifact_set_fingerprint
        ):
            raise OutputPublicationIntegrityError(
                "Reconstructed Phase-J artifact fingerprint does not match "
                "the selected Final Model Review revision."
            )

        if (
            validation_result.content_fingerprint
            != revision.validation_result_fingerprint
        ):
            raise OutputPublicationIntegrityError(
                "Reconstructed Phase-K result fingerprint does not match "
                "the selected Final Model Review revision."
            )

        try:
            self._phase_l_gate(
                artifact_set,
                validation_result,
            )
        except Exception as exc:
            raise OutputPublicationIntegrityError(
                "Reconstructed Final Model Review evidence fails the exact "
                "Phase-K -> Phase-L publication gate."
            ) from exc

        try:
            return self._writer.publish(
                artifact_set,
                validation_result,
                decision,
            )
        except Exception as exc:
            raise OutputPublicationIntegrityError(
                "Approved Final Model Review revision could not be published."
            ) from exc

    @staticmethod
    def _validate_approval_target(
        decision,
        *,
        project_id: str,
        review_id: str,
        revision_id: str,
    ) -> None:
        target = getattr(decision, "target", None)

        if (
            getattr(decision, "project_id", None) != project_id
            or getattr(decision, "decision", None)
            != "approved_for_publication"
            or getattr(target, "final_model_review_id", None)
            != review_id
            or getattr(
                target,
                "final_model_review_revision_id",
                None,
            )
            != revision_id
        ):
            raise OutputPublicationIntegrityError(
                "Human publication approval does not authorize the exact "
                "selected Final Model Review revision."
            )

    def _artifact_set_from_bundle(
        self,
        bundle,
    ) -> (
        GeneratedSysMLArtifactSet
        | AuthorityBackedGeneratedSysMLArtifactSet
    ):
        traces = bundle.artifact_set_snapshot.get(
            "traceability_entries"
        )
        authority_backed = (
            isinstance(traces, (list, tuple))
            and any(
                isinstance(item, dict)
                and "authority_references" in item
                for item in traces
            )
        )
        if authority_backed:
            try:
                artifact_set = authority_backed_artifact_set_from_json(
                    json.dumps(
                        bundle.artifact_set_snapshot,
                        ensure_ascii=False,
                        sort_keys=True,
                    )
                )
            except Exception as exc:
                raise OutputPublicationIntegrityError(
                    "Authority-backed GeneratedSysMLArtifactSet snapshot "
                    "cannot be reconstructed exactly."
                ) from exc
        else:
            artifact_set = _strict_dataclass_from_snapshot(
                GeneratedSysMLArtifactSet,
                bundle.artifact_set_snapshot,
                label="GeneratedSysMLArtifactSet snapshot",
            )

        stored_by_id = {
            item.generated_unit_id: item
            for item in bundle.generated_units
        }

        if len(stored_by_id) != len(bundle.generated_units):
            raise OutputPublicationIntegrityError(
                "Final Model Review contains duplicate stored generated-unit IDs."
            )

        reconstructed_units = []

        for unit in artifact_set.units:
            stored = stored_by_id.get(unit.unit_id)

            if stored is None:
                raise OutputPublicationIntegrityError(
                    "Generated unit from the Phase-J snapshot is missing from "
                    "the reviewed Final Model Review bytes."
                )

            if (
                stored.relative_path != unit.relative_path
                or stored.content_fingerprint
                != unit.content_fingerprint
                or stored.content != unit.content
            ):
                raise OutputPublicationIntegrityError(
                    "Reviewed generated SysML bytes do not exactly match the "
                    "persisted Phase-J artifact snapshot."
                )

            reconstructed_units.append(
                replace(
                    unit,
                    content=stored.content,
                )
            )

        if set(stored_by_id) != {
            item.unit_id for item in artifact_set.units
        }:
            raise OutputPublicationIntegrityError(
                "Final Model Review contains generated bytes outside the "
                "persisted Phase-J artifact snapshot."
            )

        return replace(
            artifact_set,
            units=tuple(reconstructed_units),
        )

    @staticmethod
    def _validation_result_from_bundle(
        bundle,
    ) -> SysMLValidationResult:
        return _strict_dataclass_from_snapshot(
            SysMLValidationResult,
            bundle.validation_result_snapshot,
            label="SysMLValidationResult snapshot",
        )


def _strict_dataclass_from_snapshot(
    cls,
    payload,
    *,
    label: str,
):
    """Reconstruct one exact nested dataclass from an asdict JSON snapshot."""

    try:
        return _convert_snapshot_value(
            cls,
            payload,
            path=label,
        )
    except OutputPublicationIntegrityError:
        raise
    except Exception as exc:
        raise OutputPublicationIntegrityError(
            f"{label} cannot be reconstructed exactly."
        ) from exc


def _convert_snapshot_value(
    expected_type,
    value,
    *,
    path: str,
):
    origin = get_origin(expected_type)
    args = get_args(expected_type)

    if expected_type is Any:
        return value

    if origin in {Union, types.UnionType}:
        if value is None and type(None) in args:
            return None

        candidates = tuple(
            item
            for item in args
            if item is not type(None)
        )

        for candidate in candidates:
            try:
                return _convert_snapshot_value(
                    candidate,
                    value,
                    path=path,
                )
            except OutputPublicationIntegrityError:
                continue

        raise OutputPublicationIntegrityError(
            f"{path} does not match the expected union contract."
        )

    if origin is tuple:
        if not isinstance(value, (list, tuple)):
            raise OutputPublicationIntegrityError(
                f"{path} must be an array."
            )

        if len(args) == 2 and args[1] is Ellipsis:
            return tuple(
                _convert_snapshot_value(
                    args[0],
                    item,
                    path=f"{path}[{index}]",
                )
                for index, item in enumerate(value)
            )

        if len(args) != len(value):
            raise OutputPublicationIntegrityError(
                f"{path} has the wrong tuple length."
            )

        return tuple(
            _convert_snapshot_value(
                item_type,
                item,
                path=f"{path}[{index}]",
            )
            for index, (item_type, item) in enumerate(
                zip(args, value)
            )
        )

    if isinstance(expected_type, type) and is_dataclass(expected_type):
        if not isinstance(value, dict):
            raise OutputPublicationIntegrityError(
                f"{path} must be an object."
            )

        field_names = {
            field.name
            for field in fields(expected_type)
        }

        if set(value) != field_names:
            missing = sorted(field_names - set(value))
            unexpected = sorted(set(value) - field_names)
            raise OutputPublicationIntegrityError(
                f"{path} fields do not match the immutable contract; "
                f"missing={missing}, unexpected={unexpected}."
            )

        hints = get_type_hints(expected_type)

        values = {
            field.name: _convert_snapshot_value(
                hints[field.name],
                value[field.name],
                path=f"{path}.{field.name}",
            )
            for field in fields(expected_type)
        }

        return expected_type(**values)

    if expected_type is bool:
        if type(value) is not bool:
            raise OutputPublicationIntegrityError(
                f"{path} must be boolean."
            )
        return value

    if expected_type is int:
        if type(value) is not int:
            raise OutputPublicationIntegrityError(
                f"{path} must be integer."
            )
        return value

    if expected_type is str:
        if not isinstance(value, str):
            raise OutputPublicationIntegrityError(
                f"{path} must be text."
            )
        return value

    if expected_type is type(None):
        if value is not None:
            raise OutputPublicationIntegrityError(
                f"{path} must be null."
            )
        return None

    if isinstance(expected_type, type):
        if not isinstance(value, expected_type):
            raise OutputPublicationIntegrityError(
                f"{path} has invalid type."
            )
        return value

    raise OutputPublicationIntegrityError(
        f"{path} uses an unsupported snapshot type contract."
    )
