"""Phase-L Final Model Review domain foundation."""

from .contracts import (
    FINAL_MODEL_REVIEW_SCHEMA_VERSION,
    calculate_final_model_review_decision_fingerprint,
    calculate_final_model_review_item_fingerprint,
    calculate_final_model_review_manifest_fingerprint,
    calculate_final_model_review_revision_fingerprint,
    calculate_review_subject_fingerprint,
    create_evidence_reference,
    create_final_model_review_decision,
    create_final_model_review_decision_target,
    create_final_model_review_item,
    create_final_model_review_manifest,
    create_final_model_review_revision,
    create_generated_unit_reference,
    validate_final_model_review_decision,
    validate_final_model_review_item,
    validate_final_model_review_manifest,
    validate_final_model_review_revision,
)
from .errors import (
    FinalModelReviewError,
    FinalModelReviewIdAllocationError,
    FinalModelReviewIntegrityError,
    FinalModelReviewNotFoundError,
    FinalModelReviewPersistenceError,
    FinalModelReviewReleaseGateError,
    FinalModelReviewValidationError,
)
from .fingerprints import (
    calculate_json_fingerprint,
    canonical_json_bytes,
    validate_sha256_fingerprint,
)
from .identifiers import (
    final_model_review_change_proposal_id_sequence,
    final_model_review_decision_id_sequence,
    final_model_review_id_sequence,
    final_model_review_item_id_sequence,
    final_model_review_revision_id_sequence,
    format_final_model_review_change_proposal_id,
    format_final_model_review_decision_id,
    format_final_model_review_id,
    format_final_model_review_item_id,
    format_final_model_review_revision_id,
    next_final_model_review_change_proposal_id,
    next_final_model_review_decision_id,
    next_final_model_review_id,
    next_final_model_review_item_id,
    next_final_model_review_revision_id,
    validate_final_model_review_change_proposal_id,
    validate_final_model_review_decision_id,
    validate_final_model_review_id,
    validate_final_model_review_item_id,
    validate_final_model_review_revision_id,
)
from .types import (
    FINAL_MODEL_REVIEW_DECISIONS,
    FINAL_MODEL_REVIEW_EVIDENCE_TYPES,
    FINAL_MODEL_REVIEW_ITEM_KINDS,
    FINAL_MODEL_REVIEW_LIFECYCLE_STATES,
    FINAL_MODEL_REVIEW_PUBLICATION_GATES,
    FINAL_MODEL_REVIEW_VALIDATION_STATUSES,
    FinalModelGeneratedUnitReference,
    FinalModelReviewDecision,
    FinalModelReviewDecisionTargetSnapshot,
    FinalModelReviewEvidenceReference,
    FinalModelReviewItem,
    FinalModelReviewManifest,
    FinalModelReviewRevision,
)

__all__ = [
    "FINAL_MODEL_REVIEW_DECISIONS",
    "FINAL_MODEL_REVIEW_EVIDENCE_TYPES",
    "FINAL_MODEL_REVIEW_ITEM_KINDS",
    "FINAL_MODEL_REVIEW_LIFECYCLE_STATES",
    "FINAL_MODEL_REVIEW_PUBLICATION_GATES",
    "FINAL_MODEL_REVIEW_SCHEMA_VERSION",
    "FINAL_MODEL_REVIEW_VALIDATION_STATUSES",
    "FinalModelGeneratedUnitReference",
    "FinalModelReviewDecision",
    "FinalModelReviewDecisionTargetSnapshot",
    "FinalModelReviewError",
    "FinalModelReviewEvidenceReference",
    "FinalModelReviewIdAllocationError",
    "FinalModelReviewIntegrityError",
    "FinalModelReviewNotFoundError",
    "FinalModelReviewPersistenceError",
    "FinalModelReviewReleaseGateError",
    "FinalModelReviewItem",
    "FinalModelReviewManifest",
    "FinalModelReviewRevision",
    "FinalModelReviewValidationError",
    "calculate_final_model_review_decision_fingerprint",
    "calculate_final_model_review_item_fingerprint",
    "calculate_final_model_review_manifest_fingerprint",
    "calculate_final_model_review_revision_fingerprint",
    "calculate_json_fingerprint",
    "calculate_review_subject_fingerprint",
    "canonical_json_bytes",
    "create_evidence_reference",
    "create_final_model_review_decision",
    "create_final_model_review_decision_target",
    "create_final_model_review_item",
    "create_final_model_review_manifest",
    "create_final_model_review_revision",
    "create_generated_unit_reference",
    "final_model_review_decision_id_sequence",
    "final_model_review_id_sequence",
    "final_model_review_item_id_sequence",
    "final_model_review_revision_id_sequence",
    "format_final_model_review_decision_id",
    "format_final_model_review_id",
    "format_final_model_review_item_id",
    "format_final_model_review_revision_id",
    "next_final_model_review_decision_id",
    "next_final_model_review_id",
    "next_final_model_review_item_id",
    "next_final_model_review_revision_id",
    "validate_final_model_review_decision",
    "validate_final_model_review_decision_id",
    "validate_final_model_review_id",
    "validate_final_model_review_item",
    "validate_final_model_review_item_id",
    "validate_final_model_review_manifest",
    "validate_final_model_review_revision",
    "validate_final_model_review_revision_id",
    "validate_sha256_fingerprint",
]


from .paths import (
    final_model_review_change_proposal_path,
    final_model_review_change_proposals_path,
    final_model_review_decision_path,
    final_model_review_decisions_path,
    final_model_review_item_path,
    final_model_review_manifest_path,
    final_model_review_path,
    final_model_review_revision_items_path,
    final_model_review_revision_path,
    final_model_review_revisions_path,
    final_model_reviews_path,
)
from .repository import FinalModelReviewRepository
from .serialization import (
    STORAGE_SCHEMA_VERSION as FINAL_MODEL_REVIEW_STORAGE_MANIFEST_SCHEMA_VERSION,
    create_revision_storage_manifest,
    final_model_review_decision_from_json,
    final_model_review_decision_to_json,
    final_model_review_item_from_json,
    final_model_review_item_to_json,
    final_model_review_manifest_from_json,
    final_model_review_manifest_to_json,
    final_model_review_revision_from_json,
    final_model_review_revision_to_json,
    revision_storage_manifest_from_json,
    revision_storage_manifest_to_json,
)
from .types import (
    FINAL_MODEL_REVIEW_STORED_FILE_ROLES,
    FinalModelReviewRepositoryIssue,
    FinalModelReviewRepositoryScanResult,
    FinalModelReviewRevisionBundle,
    FinalModelReviewRevisionStorageManifest,
    FinalModelReviewStoredFileReference,
    FinalModelReviewStoredGeneratedUnit,
)

__all__.extend([
    "FINAL_MODEL_REVIEW_STORAGE_MANIFEST_SCHEMA_VERSION",
    "FINAL_MODEL_REVIEW_STORED_FILE_ROLES",
    "FinalModelReviewRepository",
    "FinalModelReviewRepositoryIssue",
    "FinalModelReviewRepositoryScanResult",
    "FinalModelReviewRevisionBundle",
    "FinalModelReviewRevisionStorageManifest",
    "FinalModelReviewStoredFileReference",
    "FinalModelReviewStoredGeneratedUnit",
    "create_revision_storage_manifest",
    "final_model_review_decision_from_json",
    "final_model_review_decision_path",
    "final_model_review_decision_to_json",
    "final_model_review_decisions_path",
    "final_model_review_item_from_json",
    "final_model_review_item_path",
    "final_model_review_item_to_json",
    "final_model_review_manifest_from_json",
    "final_model_review_manifest_path",
    "final_model_review_manifest_to_json",
    "final_model_review_path",
    "final_model_review_revision_from_json",
    "final_model_review_revision_items_path",
    "final_model_review_revision_path",
    "final_model_review_revision_to_json",
    "final_model_review_revisions_path",
    "final_model_reviews_path",
    "revision_storage_manifest_from_json",
    "revision_storage_manifest_to_json",
])

from .read_model import (
    FinalModelReviewAgentEvidenceResolver,
    FinalModelReviewReadService,
    final_model_review_view_to_dict,
)
from .types import (
    FinalModelReviewAgentProposalView,
    FinalModelReviewCodeLocationView,
    FinalModelReviewCodeUnitView,
    FinalModelReviewDiagramEdgeView,
    FinalModelReviewDiagramNodeView,
    FinalModelReviewDiagramView,
    FinalModelReviewTraceabilityView,
    FinalModelReviewValidationFindingView,
    FinalModelReviewView,
)

__all__.extend(
    [
        "FinalModelReviewAgentEvidenceResolver",
        "FinalModelReviewAgentProposalView",
        "FinalModelReviewCodeLocationView",
        "FinalModelReviewCodeUnitView",
        "FinalModelReviewDiagramEdgeView",
        "FinalModelReviewDiagramNodeView",
        "FinalModelReviewDiagramView",
        "FinalModelReviewReadService",
        "FinalModelReviewTraceabilityView",
        "FinalModelReviewValidationFindingView",
        "FinalModelReviewView",
        "final_model_review_view_to_dict",
    ]
)


from .change_proposal import (
    CHANGE_PROPOSAL_SCHEMA_VERSION,
    ROUTE_BY_CLASSIFICATION,
    calculate_final_model_review_change_proposal_fingerprint,
    create_final_model_review_change_proposal,
    final_model_review_change_proposal_from_json,
    final_model_review_change_proposal_to_json,
    validate_final_model_review_change_proposal,
)
from .change_workflow import (
    FinalModelReviewAgentReproposalAdapter,
    FinalModelReviewChangeService,
)
from .types import (
    AGENT_REPROPOSAL_REQUEST_STATUSES,
    FINAL_MODEL_REVIEW_CHANGE_CLASSIFICATIONS,
    FINAL_MODEL_REVIEW_CHANGE_ROUTES,
    FINAL_MODEL_REVIEW_CHANGE_SURFACES,
    FinalModelReviewAgentReproposalRequest,
    FinalModelReviewChangeProposal,
    FinalModelReviewChangeRoute,
    FinalModelReviewChangeSubmission,
    FinalModelReviewChangeTarget,
)

__all__.extend(
    [
        "AGENT_REPROPOSAL_REQUEST_STATUSES",
        "CHANGE_PROPOSAL_SCHEMA_VERSION",
        "FINAL_MODEL_REVIEW_CHANGE_CLASSIFICATIONS",
        "FINAL_MODEL_REVIEW_CHANGE_ROUTES",
        "FINAL_MODEL_REVIEW_CHANGE_SURFACES",
        "ROUTE_BY_CLASSIFICATION",
        "FinalModelReviewAgentReproposalAdapter",
        "FinalModelReviewAgentReproposalRequest",
        "FinalModelReviewChangeProposal",
        "FinalModelReviewChangeRoute",
        "FinalModelReviewChangeService",
        "FinalModelReviewChangeSubmission",
        "FinalModelReviewChangeTarget",
        "calculate_final_model_review_change_proposal_fingerprint",
        "create_final_model_review_change_proposal",
        "final_model_review_change_proposal_from_json",
        "final_model_review_change_proposal_id_sequence",
        "final_model_review_change_proposal_path",
        "final_model_review_change_proposal_to_json",
        "final_model_review_change_proposals_path",
        "format_final_model_review_change_proposal_id",
        "next_final_model_review_change_proposal_id",
        "validate_final_model_review_change_proposal",
        "validate_final_model_review_change_proposal_id",
    ]
)

from .release_gate import (
    calculate_final_model_review_release_gate_fingerprint,
    evaluate_final_model_review_release_gate,
    require_final_model_review_approved_for_publication,
    require_final_model_review_ready_for_approval,
)
from .release_service import FinalModelReviewReleaseService
from .types import (
    FINAL_MODEL_REVIEW_RELEASE_STATUSES,
    FinalModelReviewReleaseApproval,
    FinalModelReviewReleaseBlocker,
    FinalModelReviewReleaseGateResult,
)

__all__.extend(
    [
        "FINAL_MODEL_REVIEW_RELEASE_STATUSES",
        "FinalModelReviewReleaseApproval",
        "FinalModelReviewReleaseBlocker",
        "FinalModelReviewReleaseGateError",
        "FinalModelReviewReleaseGateResult",
        "FinalModelReviewReleaseService",
        "calculate_final_model_review_release_gate_fingerprint",
        "evaluate_final_model_review_release_gate",
        "require_final_model_review_approved_for_publication",
        "require_final_model_review_ready_for_approval",
    ]
)
